In [1]:
from jijbench import Experiment

# JijModelingの場合

In [2]:
import jijzept as jz
import jijmodeling as jm

d = jm.Placeholder("d", dim=1)
n = d.shape[0]

x = jm.Binary("x", shape=(n, ))

problem = jm.Problem("sample")

i = jm.Element("i", (0, n))

problem += jm.Sum(i, d[i]*x[i])
problem += jm.Constraint("onehot", x[:] == 1)
problem += jm.Constraint("onehot2", x[:] == 1)

data = {"d": [1, 2, -1, -3, -1]}

sampler = jz.JijSASampler(config="/home/azureuser/.config/jijzept/config.toml")
response = sampler.sample_model(problem, data, {'onehot': 4},  num_reads=5)
decoded = problem.decode(response, data, {})
# アーティファクトのサンプル
sample_artifacts = {"hoge": {"fuga": 1}}

# ここからExperiment
benchmark_id="test_jm"
experiment = Experiment(benchmark_id=benchmark_id)
with experiment.start() as e:
    for param in [10, 100, 1000]:
        for step in range(3):
            # solverは上のsample_responseを返す想定
            # sample_response = solver()
            # experiment.tableに登録するrecordを辞書型で作成
            record = {
                "step": step,
                "param": param,
                "decoded": decoded,
            }
            experiment.insert_into_table(record)
            experiment.update_artifact(sample_artifacts)
    experiment.save()

uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 03d4b188874c43f89443375224a6d5a0.

In [5]:
experiment.table

,run_id,experiment_id,benchmark_id,energy,energy_min,energy_mean,energy_std,objective,obj_min,obj_mean,...,step,param,onehot_violations,onehot_violation_min,onehot_violation_mean,onehot_violation_std,onehot2_violations,onehot2_violation_min,onehot2_violation_mean,onehot2_violation_std
0,73fe0a37-6570-41a5-b83f-06abd7f80353,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,0,10,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
1,99b07685-f58a-4b7a-b2b7-b6276ede71a9,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,1,10,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
2,2b80ea1a-fae0-499b-802e-ab504d3f9bfd,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,2,10,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
3,fe7481a3-ee1c-4c3b-8666-3cb5627c5fb5,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,0,100,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
4,d90401fd-b9d8-45b3-adde-ccc08c0b9cd8,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,1,100,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
5,f275ff91-6d46-4c0c-88f0-25b910425105,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,2,100,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
6,4e87a0e3-1834-48ca-97e9-29b37286079d,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,0,1000,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
7,7fb4f917-ca8d-412f-976a-306dc08ffef3,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,1,1000,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
8,e035c194-f8b0-4377-9d25-a99f7f11f84f,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,2,1000,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0

In [10]:
experiment.artifact

{'hoge': {'fuga': 1}}

In [7]:
# ロードする場合
# experiment_idがuuidになっているので少しめんどくさい。
# experiment_idは自分でも設定できるのでよしなにやってください。
experiment_id = "fb334682-939f-40b8-8440-0da73f8e81a6"
experiment = Experiment(experiment_id=experiment_id, benchmark_id=benchmark_id)
experiment.load()

In [8]:
# 現状nanも表示されるので不要な場合はdropnaなどで消してください。
experiment.table

,run_id,experiment_id,benchmark_id,energy,energy_min,energy_mean,energy_std,objective,obj_min,obj_mean,...,step,param,onehot_violations,onehot_violation_min,onehot_violation_mean,onehot_violation_std,onehot2_violations,onehot2_violation_min,onehot2_violation_mean,onehot2_violation_std
0,73fe0a37-6570-41a5-b83f-06abd7f80353,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,0,10,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
1,99b07685-f58a-4b7a-b2b7-b6276ede71a9,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,1,10,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
2,2b80ea1a-fae0-499b-802e-ab504d3f9bfd,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,2,10,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
3,fe7481a3-ee1c-4c3b-8666-3cb5627c5fb5,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,0,100,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
4,d90401fd-b9d8-45b3-adde-ccc08c0b9cd8,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,1,100,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
5,f275ff91-6d46-4c0c-88f0-25b910425105,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,2,100,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
6,4e87a0e3-1834-48ca-97e9-29b37286079d,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,0,1000,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
7,7fb4f917-ca8d-412f-976a-306dc08ffef3,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,1,1000,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0
8,e035c194-f8b0-4377-9d25-a99f7f11f84f,fb334682-939f-40b8-8440-0da73f8e81a6,test_jm,"[-2.9999999999999982, -2.9999999999999982, -2....",-3.0,-3.0,0.0,"[-3.0, -3.0, -3.0, -3.0, -3.0]",-3.0,-3.0,...,2,1000,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",0.0,0.0,0.0

In [9]:
experiment.artifact

{'hoge': {'fuga': 1}}

# OpenJijの場合

In [3]:
import openjij as oj

sampler = oj.SASampler()
pyq_obj = problem.to_pyqubo(data, {})
bqm = pyq_obj.compile().to_bqm(feed_dict={"onehot": 4, "onehot2": 4})
sampler = oj.SASampler(num_reads=5)
response = sampler.sample(bqm)
sample_artifacts = {"hoge": {"fuga": 1}}

# ここからExperiment"
benchmark_id = "test_oj"
experiment = Experiment(benchmark_id=benchmark_id)
with experiment.start() as e:
    for param in [10, 100, 1000]:
        for step in range(3):
            # solverは上のsample_responseを返す想定
            # sample_response = solver()
            # experiment.tableに登録するrecordを辞書型で作成
            record = {
                "step": step,
                "param": param,
                "response": response,
            }
            experiment.insert_into_table(record)
            experiment.update_artifact(sample_artifacts)
    experiment.save()

In [4]:
experiment.table

,run_id,experiment_id,benchmark_id,energy,energy_min,energy_mean,energy_std,objective,obj_min,obj_mean,obj_std,num_occurances,num_feasible,num_samples,{const_name}_violations,{const_name}_violation_min,{const_name}_violation_mean,{const_name}_violation_std,step,param
0,9fac365f-0935-47a0-a2be-0970562d07f2,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,0,10
1,fdb63ac5-8c3e-4575-b6df-23a8c1538a31,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,1,10
2,3c47c7eb-85a7-4ce4-8327-fa4a0b6cde27,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,2,10
3,d50da193-f914-41e6-a334-27b89e956414,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,0,100
4,f83f2e18-d573-4e5b-bb3a-aeb63a4fa3bc,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,1,100
5,34859c73-3ad5-4118-b1d5-37a8b172575f,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,2,100
6,909373c1-ba3a-42b8-bb85-7ff9bf60d304,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,0,1000
7,3c1d0296-d73d-495e-84f3-fd22498906b1,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,1,1000
8,d126b652-c02c-4fcf-a173-264993a5906e,5a3fd0ff-ec98-44db-8f73-b1e297a960ce,test_oj,"[-3.0, -3.0, -3.0, -1.0, -3.0]",-3.0,-2.6,0.8,NaN,NaN,NaN,NaN,"[1, 1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,2,1000