In [1]:
import jijbench as jb

In [2]:
""" 
    experiment = Experiment():
    for num_reads in [1, 2]:
        for num_sweeps in [10]:
            with experiment:
                ...
                
"""

bench = jb.Benchmark(
    params={"num_reads": [1, 10], "num_sweeps": [10]},
    solvers="SASampler",
    targets="Knapsack",
)
bench.run()


""" 
bench = jb.Benchmark(
    params={"num_reads": [1, 2], "num_sweeps": [10]},
    solver="JijSASampler",
    targets=["TSP", "Knapsack"] # デフォルト複数
)
bench.run()

bench = jb.Benchmark(
    params={"num_reads": [1, 2], "num_sweeps": [10]},
    solver="JijSASampler",
    targets=[t1, t2] # カスタムver
)
bench.run() """

' \nbench = jb.Benchmark(\n    params={"num_reads": [1, 2], "num_sweeps": [10]},\n    solver="JijSASampler",\n    targets=["TSP", "Knapsack"] # デフォルト複数\n)\nbench.run()\n\nbench = jb.Benchmark(\n    params={"num_reads": [1, 2], "num_sweeps": [10]},\n    solver="JijSASampler",\n    targets=[t1, t2] # カスタムver\n)\nbench.run() '

In [3]:
bench.table.iloc[:, :20]

,benchmark_id,experiment_id,run_id,timestamp,energy,energy_min,energy_mean,energy_std,objective,obj_min,obj_mean,obj_std,num_occurances,num_reads,num_sweeps,num_feasible,num_samples,sampling_time,execution_time,problem_name
0,bedf23ee-8a04-47ba-9473-f9a3226cfc30,ce972bf3-1311-48f1-95b0-27e446066192,bf8413cb-f0ad-4f88-b4d7-58662d07f5e6,2022-03-31 20:59:01.014671,[-200.0],-200.0,-200.0,0.0,[-200.0],-200.0,-200.0,0.0,[1],1,10,1,1,143.202022,55.701472,knapsack
1,bedf23ee-8a04-47ba-9473-f9a3226cfc30,ce972bf3-1311-48f1-95b0-27e446066192,5a82d816-dbbb-4f9d-b2d8-505fb284d735,2022-03-31 20:59:01.071588,"[-206.0, -111.0, -85.0, -336.0, -318.0, -428.0...",-428.0,-215.6,123.579286,"[-211.0, -131.0, -85.0, -336.0, -338.0, -428.0...",-428.0,-244.6,100.886273,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",10,10,10,10,754.010864,22.420008,knapsack

In [3]:
bench.table.dropna(how="all", axis=1).iloc[:, -20:]

,energy_mean,energy_std,objective,obj_min,obj_mean,obj_std,num_occurances,num_reads,num_sweeps,num_feasible,num_samples,sampling_time,execution_time,problem_name,instance_name,solver,knapsack_constraint_violations,knapsack_constraint_violation_min,knapsack_constraint_violation_mean,knapsack_constraint_violation_std
0,4205.0,0.0,[-0.0],-0.0,0.0,0.0,[1],1,10,1,1,317.004509,201.102346,knapsack,f1_l-d_kp_10_269,openjij_sa_sampler_sample,[0.0],0.0,0.0,0.0

In [4]:
bench.evaluate()

/home/azureuser/JijBenchmark/jijbench/evaluation/evaluation.py:132: RuntimeWarning: divide by zero encountered in log
  return np.log(1 - pr) / np.log(1 - ps) * x.execution_time
/home/azureuser/JijBenchmark/jijbench/evaluation/evaluation.py:132: RuntimeWarning: divide by zero encountered in double_scalars
  return np.log(1 - pr) / np.log(1 - ps) * x.execution_time
/home/azureuser/JijBenchmark/jijbench/evaluation/evaluation.py:132: RuntimeWarning: divide by zero encountered in log
  return np.log(1 - pr) / np.log(1 - ps) * x.execution_time

,success_probability,feasible_rate,residual_energy,TTS(optimal),TTS(feasible),TTS(derived)
0,1.0,0.0,-0.866259,0.0,-inf,0.000000
1,1.0,0.0,-0.865241,0.0,-inf,26847.936029

In [5]:
bench.table.dropna(how="all", axis=1).iloc[:, -15:]

,solver,onehot_time_violations,onehot_time_violation_min,onehot_time_violation_mean,onehot_time_violation_std,onehot_location_violations,onehot_location_violation_min,onehot_location_violation_mean,onehot_location_violation_std,success_probability,feasible_rate,residual_energy,TTS(optimal),TTS(feasible),TTS(derived)
0,openjij_sa_sampler_sample,[29.0],29.0,29.0,0.0,[9.0],9.0,9.0,0.0,1.0,0.0,-0.866259,0.0,-inf,0.000000
1,openjij_sa_sampler_sample,"[28.0, 29.0]",28.0,28.5,0.5,"[10.0, 11.0]",10.0,10.5,0.5,1.0,0.0,-0.865241,0.0,-inf,26847.936029

In [ ]:
# TODO ベンチマークの設定をファイル出力しておく。再実験可能なようにするため

In [4]:
import jijbench as jb

# 複数ソルバー
def solver1():
    return 100, 1000, 10000

def solver2(x, a=2, b=3):
    return f"(x, a, b) = ({x}, {a}, {b})"


""" 
for solver in [solver1, solver2, "SASampler"]:
    experiment = Experiment()
    for num_reads in [1, 2, 3]:
        for num_sweeps in [10]:
            for x in [100, 200]:
                with experiment:
                    ret = solver(num_reads=num_reads, num_sweeps=num_sweeps, x=x) """

bench = jb.Benchmark(
    {"num_reads": [1], "num_sweeps": [10], "x": [100, 200]},
    solvers = [solver1, solver2, "SASampler"],
    targets=["TSP", "Knapsack"]
)
bench.run()

In [8]:
bench.experiments

[<jijbench.experiment.experiment.Experiment at 0x7fc0c4b00100>,
 <jijbench.experiment.experiment.Experiment at 0x7fc0c32e9dc0>,
 <jijbench.experiment.experiment.Experiment at 0x7fc0c4b47340>]

In [5]:
bench.table.iloc[:, -15:]

,num_samples,sampling_time,execution_time,problem_name,instance_name,opt_value,solver,x,solver_return_values[0],solver_return_values[1],solver_return_values[2],knapsack_constraint_violations,knapsack_constraint_violation_min,knapsack_constraint_violation_mean,knapsack_constraint_violation_std
0,NaN,NaN,NaN,knapsack,f1_l-d_kp_10_269,NaN,solver1,100.0,100.0,1000.0,10000.0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,knapsack,f1_l-d_kp_10_269,NaN,solver1,200.0,100.0,1000.0,10000.0,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,knapsack,f1_l-d_kp_10_269,NaN,solver2,100.0,"(x, a, b) = (100, 2, 3)",NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,knapsack,f1_l-d_kp_10_269,NaN,solver2,200.0,"(x, a, b) = (200, 2, 3)",NaN,NaN,NaN,NaN,NaN,NaN
0,1,138.60222,54.400414,knapsack,f1_l-d_kp_10_269,NaN,openjij_sa_sampler_sample,100.0,NaN,NaN,NaN,[0.0],0.0,0.0,0.0
1,1,134.002417,53.900294,knapsack,f1_l-d_kp_10_269,NaN,openjij_sa_sampler_sample,200.0,NaN,NaN,NaN,[0.0],0.0,0.0,0.0

In [13]:
bench.evaluate()

/home/azureuser/JijBenchmark/jijbench/evaluation/evaluation.py:132: RuntimeWarning: divide by zero encountered in log
  return np.log(1 - pr) / np.log(1 - ps) * x.execution_time
/home/azureuser/JijBenchmark/jijbench/evaluation/evaluation.py:132: RuntimeWarning: divide by zero encountered in double_scalars
  return np.log(1 - pr) / np.log(1 - ps) * x.execution_time
/home/azureuser/JijBenchmark/jijbench/evaluation/evaluation.py:132: RuntimeWarning: divide by zero encountered in log
  return np.log(1 - pr) / np.log(1 - ps) * x.execution_time

,success_probability,feasible_rate,residual_energy,TTS(optimal),TTS(feasible),TTS(derived)
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
0,1.0,0.0,-0.850645,0.0,-inf,0.0
1,1.0,0.0,-0.864223,0.0,-inf,0.0

In [14]:
bench.compare(key="solver", values=["experiment_id", "num_reads", "num_sweeps", "energy", "feasible_rate", "TTS(feasible)"])

                               experiment_id  \
solver             openjij_sa_sampler_sample
0       5f3fc20b-e352-4459-b00b-3931a492afcf
1       5f3fc20b-e352-4459-b00b-3931a492afcf

                                              \
solver                               solver1
0       120d800f-4480-4324-97e4-86be412ec45e
1       120d800f-4480-4324-97e4-86be412ec45e

                                                             num_reads  \
solver                               solver2 openjij_sa_sampler_sample
0       56df9ab6-02ad-4e80-af22-86ef4c66134c                         1
1       56df9ab6-02ad-4e80-af22-86ef4c66134c                         1

                                      num_sweeps                  \
solver solver1 solver2 openjij_sa_sampler_sample solver1 solver2
0            1       1                        10      10      10
1            1       1                        10      10      10

                          energy                             feasible_rate  \
solver openjij_sa_sampler_sample solver1 solver2 openjij_sa_sampler_sample
0                        [220.0]     NaN     NaN                       0.0
1                        [200.0]     NaN     NaN                       0.0

                                   TTS(feasible)
solver solver1 solver2 openjij_sa_sampler_sample solver1 solver2
0          NaN     NaN                      -inf     NaN     NaN
1          NaN     NaN                      -inf     NaN     NaN

In [2]:
# 複数ソルバー
def solver1():
    return 100, 1000, 10000

def solver2(qubo, a=2, b=3):
    return f"(x, a, b) = ({qubo}, {a}, {b})"

# dictが引数の場合はtableには保存しない。
bench = jb.Benchmark(
    {"num_reads": [1, 2], "num_sweeps": [10], "qubo": [{"h": [1, 2, 3]}, {"h": [10, 20, 30]}]},
    solvers = [solver1, solver2],
    targets="TSP"
)
bench.name_solver_ret(
    {"solver1": ["r1", "r2", "r3"], "solver2": ["r1"], "SASampler": ["r1", "r2"]}
)
bench.run()

In [3]:
bench.table

,run_id,experiment_id,benchmark_id,timestamp,energy,energy_min,energy_mean,energy_std,objective,obj_min,...,sampling_time,execution_time,problem_name,instance_name,opt_value,solver,qubo,r1,r2,r3
0,c1250999-45c8-4daf-ac39-665eb3df99c5,64cca972-ba2b-4878-b428-f0122759549e,30887ce7-3068-4af8-a218-901f07bd7836,2022-03-28 17:44:44.792485,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,travelling_salesman,ftv35,1473.0,solver1,"{'h': [1, 2, 3]}",100.0,1000.0,10000.0
1,ccc2f0d1-39fc-4b87-89a5-6e3b0b417e70,64cca972-ba2b-4878-b428-f0122759549e,30887ce7-3068-4af8-a218-901f07bd7836,2022-03-28 17:44:44.809722,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,travelling_salesman,ftv35,1473.0,solver1,"{'h': [10, 20, 30]}",100.0,1000.0,10000.0
2,a92c978c-6d35-43e1-a8c7-7b561c996c26,64cca972-ba2b-4878-b428-f0122759549e,30887ce7-3068-4af8-a218-901f07bd7836,2022-03-28 17:44:44.817980,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,travelling_salesman,ftv35,1473.0,solver1,"{'h': [1, 2, 3]}",100.0,1000.0,10000.0
3,dc33a115-82d7-42c8-9ffd-1621abaa193a,64cca972-ba2b-4878-b428-f0122759549e,30887ce7-3068-4af8-a218-901f07bd7836,2022-03-28 17:44:44.826308,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,travelling_salesman,ftv35,1473.0,solver1,"{'h': [10, 20, 30]}",100.0,1000.0,10000.0
0,77267485-fe36-4128-8088-e5df88b43c05,921a71a5-21c9-4523-8355-7e56435d239e,30887ce7-3068-4af8-a218-901f07bd7836,2022-03-28 17:44:44.837126,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,travelling_salesman,ftv35,1473.0,solver2,"{'h': [1, 2, 3]}","(x, a, b) = ({'h': [1, 2, 3]}, 2, 3)",NaN,NaN
1,6c4f3990-a705-4dae-98b7-2d4fb63a24b0,921a71a5-21c9-4523-8355-7e56435d239e,30887ce7-3068-4af8-a218-901f07bd7836,2022-03-28 17:44:44.849977,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,travelling_salesman,ftv35,1473.0,solver2,"{'h': [10, 20, 30]}","(x, a, b) = ({'h': [10, 20, 30]}, 2, 3)",NaN,NaN
2,2a8fd5ec-e6df-401c-9bf0-c5c4a0a1e9cb,921a71a5-21c9-4523-8355-7e56435d239e,30887ce7-3068-4af8-a218-901f07bd7836,2022-03-28 17:44:44.858099,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,travelling_salesman,ftv35,1473.0,solver2,"{'h': [1, 2, 3]}","(x, a, b) = ({'h': [1, 2, 3]}, 2, 3)",NaN,NaN
3,b84144eb-e2d2-415b-b0fe-bf52d16d7841,921a71a5-21c9-4523-8355-7e56435d239e,30887ce7-3068-4af8-a218-901f07bd7836,2022-03-28 17:44:44.865284,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,travelling_salesman,ftv35,1473.0,solver2,"{'h': [10, 20, 30]}","(x, a, b) = ({'h': [10, 20, 30]}, 2, 3)",NaN,NaN

In [22]:
import jijbench as jb


def updater(multiplier=1):
    next_multiplier = 5 * multiplier
    return next_multiplier

bench = jb.Benchmark(
    {"num_reads": [1], "num_sweeps": [10], "step" : [1, 2, 3]},
    solver = updater
)
bench.name_solver_ret(
    {"updater": ["response", "decoded", "multiplier"]}
)
bench.run()


""" 
experiment = Experiment()
for num_reads in [1]:
    for num_sweeps in [10]:
        for step in [1, 2, 3]:
            kwargs = {"num_reads": num_reads, "num_sweeps": num_sweeps, "step": step}
            with experiment:
                ret = updater(**kwargs)
                # ret = 5
                ret = name_ret(ret, solver_ret_names)
                # ret = {"solver_return_value[0]": 5}
                kwargs |= ret
                #kwargs = {"num_reads": num_reads, "num_sweeps": num_sweeps, "step": step, "multiplier": 5}
"""

' \nexperiment = Experiment()\nfor num_reads in [1]:\n    for num_sweeps in [10]:\n        for step in [1, 2, 3]:\n            kwargs = {"num_reads": num_reads, "num_sweeps": num_sweeps, "step": step}\n            with experiment:\n                ret = updater(**kwargs)\n                # ret = 5\n                ret = name_ret(ret, solver_ret_names)\n                # ret = {"solver_return_value[0]": 5}\n                kwargs |= ret\n                #kwargs = {"num_reads": num_reads, "num_sweeps": num_sweeps, "step": step, "multiplier": 5}\n'

In [23]:
bench.table

,run_id,experiment_id,benchmark_id,timestamp,energy,energy_min,energy_mean,energy_std,objective,obj_min,...,num_feasible,num_samples,sampling_time,execution_time,problem_name,instance_name,opt_value,solver,step,multiplier
0,ade043bb-75f6-4688-8769-29c88cd97cc1,cb965b10-e4a3-492a-9705-f9f2ddf72a82,d8488512-9c93-46c8-bb06-31b75444c7cd,2022-03-28 03:28:12.486117,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,travelling_salesman,ftv35,1473.0,updater,1.0,5.0
1,9cf3e7d6-7fa7-4240-84b5-e04d65db8195,cb965b10-e4a3-492a-9705-f9f2ddf72a82,d8488512-9c93-46c8-bb06-31b75444c7cd,2022-03-28 03:28:12.498000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,travelling_salesman,ftv35,1473.0,updater,2.0,25.0
2,f597286e-325b-40f5-b94b-7de164068b2f,cb965b10-e4a3-492a-9705-f9f2ddf72a82,d8488512-9c93-46c8-bb06-31b75444c7cd,2022-03-28 03:28:12.506313,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,travelling_salesman,ftv35,1473.0,updater,3.0,125.0

In [ ]:
import jijbench as jb
import jijmodeling as jm


def solver1():
    return 100, 1000, 10000

def solver2(qubo, a=2, b=3):
    return f"(x, a, b) = ({qubo}, {a}, {b})"

def gen_model1():
    d1 = jm.Placeholder("d")
    x = jm.Binary("x", shape=(2,))
    problem = jm.Problem("model1")
    problem += x[0] + d1 * x[1]
    return problem

def gen_model2():
    d2 = jm.Placeholder("d")
    x = jm.Binary("x", shape=(2,))
    problem = jm.Problem("model2")
    problem += x[0] + d2 * x[1]
    problem += jm.Constraint("onehot", x[:] == 1)
    return problem


# 今リリースされてるやつでは...
# (instance_name, ph_value)
targets = {
    gen_model1(): [("model1_case1", {"d1": 1}), ("model1_case2", {"d1": 2})],
    gen_model2(): [("model2_case1", {"d2": 10})],
}

# 以下に変更予定
#problemはjijmodelingのproblem
#nstanceは[(instance_name, ph_value),...] 
t1 = jb.JijModelingTarget(
    problem=gen_model1(),
    instance=[("model1_case1", {"d1": 1}), ("model1_case2", {"d1": 2})]
    )

t2 = jb.JijModelingTarget(
    problem=gen_model2(),
    instance=("model2_case1", {"d2": 10})
)

# t3 = jb.PyQUBOTarget()
# t4 = jb.QUBOTarget(qubo=qubo, bias=bias)

# 他にPyQUBOTarget, QUBOTargetがある。

bench = jb.Benchmark(
    {"num_reads": [3, 4, 5], "num_sweeps": [10], "x": [100, 200]},
    solver=[solver1, solver2],
    targets=[t1, t2]
)
bench.run()

In [ ]:
bench.table.dropna(how="all", axis=1)

In [4]:
import jijbench as jb

bench = jb.Benchmark(
    params={"num_reads": range(5, 100, 5), "num_sweeps": range(10, 100, 10)},
    solvers="JijSASampler",
    targets="Knapsack",
    jijzept_config="/home/azureuser/.config/jijzept/config.toml"
)
bench.run(sync=True)

uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 56fdc7921d654e6294c5ada94782fb8f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is fa118dc060e54a40b2d69162d40c00fd.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is d32d7390ac54445e9cc214904778f6e7.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9fc925b82fc34006941c4a902e0f8686.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 957b9fcc667648c19effbce99631e954.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 5a9ae7e02aae4f60882441ebe6228902.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is cbabc6ad86da4acc8d0a338820cfc047.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 32e758ea4bc341a49cb1d1e287417ee7.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is bb428cfb31304312896a6a4dfec6a4a3.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is de33e64efdfe4cce896dba586ee0f2a8.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 359f7b7d1d9e4606a9dfb9e444d5802b.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 8bc97e6710b646fdb1deb5a24bb0d71f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 8bc812a9e2364515a9a550874585f6a0.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9c87f80f4de5400fb9c193f65a437d56.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 61b29078e1924efe9f917250aabd92ec.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is df770ef3d1ba4dc78c760e8e4675813d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is a717e2b84dc84ae5b3e45fe604a7e3d3.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is b0ebe9833d12405e82d6e2d153e9436a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 726777d6cdc24698b38ad15fd7e6900b.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 1fbb136f153948a1be341732d5d2b782.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 5b864d9d12774bc798fcf3a6cc99efde.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 53efda91070f41debccc41def5e846ae.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 97730a39ea3843c8a5dc5931745768c6.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is bfee373c673d41ccb56ed23ab3546499.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is edbdb3cee5b2458bb9932ea79046dbf9.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 6b4accdf76f14947875bf6800af4d3ce.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 030ccc2eae4240ed92ecc9ec9f34db88.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is ef6cb82b608040d3b9283b2bc2ede253.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 27dc1a45372c4580917f89d5b43481fc.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 31ae8308cbf342c38e3b66d0c3c73ed6.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e42fdba628454810a89dde69cb788f7b.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is ec53e274ec28476e836cc6cf471b7e78.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is b0465b94514249b192106075ac06294a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is b5a1c785383a40e3ae1aae7758ee9af1.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 172b1fc3fef34f2a9d6092608ed989f5.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 0144d3a243744adda40e1f25564c3a6b.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is c1891da3dd80433086e453979d6fd12e.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is fc7cf4c31db84a3cbb5e4673a535096a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 76bd4630ba234dfda61ae632c737ee2c.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 0cde09dd42ba44069e01462163685db1.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is ea3f4cf7bd5a4fe0bb933556576cddc7.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 59152d210d2e4e83ad87f5c7bb816564.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 16ac0826674942948d5496988e4980f7.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 2690a5af34ac4df1b9b019e325e26794.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9bd1baac5af64b3fba26bf5a37b79735.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is df2c941bf30d470e8a998312bfe4da17.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 8ee1df2f5fb740168f259401eae765e4.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is fedcc427074d45c189faecf9f527754e.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is c06039bab71444d0a40dbab31e96a603.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is a17a2b76b4ce4ad9a7b9940881782ccb.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is b254d93264624f76a089b0292ae5be60.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 744a1eef2c9745b08669e5ba0035f09d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is c822963a13ad4dad9ba0287d4d4ddd64.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 69017917d35b4df983f07925d8d7c06f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is f423cfd35f9d4563ad1906fde1552c1a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 2010d472a4dd45d2a41826b3abf669c5.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 20642795274d429d859a3a8066d03aac.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e4f6365cd50f41d280908d090e0ba6ae.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is d1dee3ad9836441584f1a8a16854c151.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is caddddd388164d489d8c00878aa8a046.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is b88092f930504a61bd378f998b603dc8.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is c56250b8d2f049b49d2fab301c1aba70.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 108b5fa116c84d0f9fb11252f9d4483d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is fa48c24e415049ce98902116f1130824.
running...
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 3b9b343d9e504616ae167e0681926fd5.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is aa3ced22a1f94dc5977f6f0c25d09285.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 7abaff27e1c6404581d165d5e538252e.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 1fee6e7ad49a4352a2653137dacac0f3.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e7af6933299d440eae7579ddcb0fcb4b.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 937481bab2ab4ea39d7e4fcaa0ec2300.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 31621950b25b4de4bc24ec4594e4f640.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 942c374d091340f4984c5d6a191c3a6d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 168e1390f4f741149937a2c2f7dea948.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e2c8293afcc340d1a419d2e5d8bd8455.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is fa009ad7b2a347889da29ae447bc74ab.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is f1f2ee0534c64eebb98f51c5b8230c4e.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 443d2e9d47a641d48a193eb069c5aec8.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 8084fc7aa3ac45d1874bdddfdca42e2c.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is ef86cb86cd374854a108bb1dd611e69d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 8893998a9c184b23bbddb432442ecb58.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 12129d3520d940809697ae7d1ec21e53.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 95f892a1cf4846d79821b422a9b76f40.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9d4e8868d09c4137adbd5d2570bfbc59.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is d6ad5731ab4b4f2398d47ad391e99625.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 6cd82ee3b56d43a0ae25de95e5f1a9ee.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 0aa2636fef174222bc6a74a1863fa732.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9d74b694c1264e30b29deaa8d49116f3.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is aa7497af1eef441d8259e7101e1cd94f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 009df5a0f4b94a1e844fed23fbfd2c3a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 4e5baceaf1ee4095a3a19278b3a20567.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is cfd5ec106c7047f2a703ba8dae7fecb7.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is dd9b4ec6086446a386c3e0900eea5031.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is c8cdb1f14f3e4885b32ed4a89edbbe1f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is f257fa5dbf884824b31ceedb68c8803a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9069aa351cc14d2590e997fd2d9bcf6c.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 618678b407db4dcfbc123f3d1c4ec0cd.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 111776a69b2c47d48396b130eac03328.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is dc34d257b3b04b01a19877c80b3ba06d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e39bd96a55cc43cd910627d699cf1c0d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 280c406293cc4718aeb0d3280b4ec19a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 350c580338714c9f95108b442c348a03.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 7e60a65491c74f9d9c0c3478dd98a30a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 27cab09a7c1b495496073f180ea3c3ef.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 66cae12ea52442cea8ca55f144a9a89b.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 0c1381f2057843e1aa8452f089c7628f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 3b7939e3a75b44e99f3768b1a0fd1894.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9f6c98fda3894be2a37776e8ba188ec2.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9bd63e1c98654f9ebc4bd0821454517d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is ed594230b4ce45769d3c337bba5f3686.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 0ba9734016c448ddaf1128fb3f41a9ef.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 57286a1cb11c4e7585e843befe2f3305.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 6dbefdefb52440ca8e02ad4c45d1de69.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is d74917d41f244a30ad4b16d6947ad359.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 5192ebc962824050be8439b7a5cc11d3.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 2f716e6f5f7e4788b15d467f5b0952b5.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 0edbd953323c4267ac281c9f2575956b.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 659ca84bd76d4755bf46db42907c5062.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 230c96bfbf0d47daa0f3d034d744b14a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 907392eecc91449a95712bc142efcdbf.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 47cc9bc86de54f2b98fd65796c0620ba.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 5decd3d1785d4238bb697d9e2e4451d4.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is f09459e613a74f58864706676d607ad3.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 1c4f5a005cb94822ba7c98a77c78bd53.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 2ddfac1bc0b742bea1829b8877ee5e0a.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 7f62fcb5c04a4028a1cbe1fcb67ec7bc.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is cb5a8f67e7a941b4a59ee04b09e3d6e1.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is f492358f7d5e471296766c37083568a5.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 65d73e9245184e6c9bae21eaa1b3fa43.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 34cc8feded094b3cbd1d878abd3d814d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is c4b909e6311745eb84cca401b1458724.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 3c1ed202e91249219243d1980080b5fd.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is ad3efc50abfb43e983b299acdc085737.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 48ad4096f8d94a778b53598ba19d2b6f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e7d5150ee8a64db6a515e8286a7424a4.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is b0e572b7280143d4a25e03a395b6a5d1.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is ca0e0fd2073247f4a468f3c9042fef8d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 66bd12b250dc4a29b4ccc28da3384b80.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is aa7af0371bef4d98b858959b1256b676.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e5c54157662d45b39da9661f328a379c.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 54ca3a9534b5421dab58d0852d5e7240.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 70a2cd7908564e4493b21f477b632e87.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e046db132a574a888ac31cf45b99054f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is e2d51862376e4a5bad44be75b9fb728d.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 69846157f54e43a784282022030aebc5.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is eed39aa98f5f4f8c95ab05ecc3c55409.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 900c5eb8b9a14f988460002a12c7c6b2.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 8181a703197c4750a4643f1db9f05ba0.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 6a1c3d1454c74662a5b4751c9e7ba64b.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is c4b096b37d154e44b559bd04e566bf40.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 3606749b952d43c2ac7d8ca5c2bc22a2.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 3d97dbc7a50c431aa277229fbd94a747.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 6de577d7104d49ce9b15a0993f68dded.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is ba1700ea4e7d4a119f0f3ac3a58d22ef.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 2ec3a956a4c142498ca2e151c58c6f59.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is b6f105682aaa43deb69c6c43a4370724.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 5fb32cf7e49b416ea1b12b8a35e12904.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 7100f723434c42b2b5d32482f0ff5f84.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 2b4934aefd4048349a474af38068b28f.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is bd83a8628f624671a6bf04d1e8f928b6.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 086a8142d0514642a8045ea8d9ffc9e5.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is bf694a7c7dab404784724d4951028769.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is bcc5e1d30b3f4ca68ca924ebcef9d783.
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 7b8dc3d8f3494ba9bcddbef15f3e827d.
uploading instance ...
submitting query ...
submitted to the queue.

In [ ]:
bench.table

In [4]:
import jijbench as jb

bench = jb.Benchmark(
    params={"num_reads": range(5, 15, 5), "num_sweeps": range(10, 20, 10)},
    solvers="JijSASampler",
    targets="Knapsack",
    jijzept_config="/home/azureuser/.config/jijzept/config.toml"
)
bench.run(sync=False)

uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 46f341c0fb67490e8d9e04e9b3d53d78.
You can access the solution by
>>> a = XXXSampler(config=...)
>>> a.get_result("46f341c0fb67490e8d9e04e9b3d53d78")
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 8143b9b2c95f4e2bb1ef2ac3163179b7.
You can access the solution by
>>> a = XXXSampler(config=...)
>>> a.get_result("8143b9b2c95f4e2bb1ef2ac3163179b7")

In [5]:
bench.table.iloc[:, :20]

,benchmark_id,experiment_id,run_id,timestamp,energy,energy_min,energy_mean,energy_std,objective,obj_min,obj_mean,obj_std,num_occurances,num_reads,num_sweeps,num_feasible,num_samples,sampling_time,execution_time,problem_name
0,708d6bec-ecb6-4575-9be9-80583c4f4473,bca038aa-f1d8-4e59-866c-903936d9c663,3802eb65-5754-4efb-a624-6c7f9205ac56,2022-03-31 20:59:42.682231,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0]",-539.0,-539.0,0.0,"[1, 1, 1, 1, 1]",5,10,0,5,163.404271,32.680854,knapsack
1,708d6bec-ecb6-4575-9be9-80583c4f4473,bca038aa-f1d8-4e59-866c-903936d9c663,77dc04cc-e3cc-4e8b-817f-c80d791a584c,2022-03-31 20:59:44.757619,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0, -539....",-539.0,-539.0,0.0,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",10,10,0,10,274.701044,27.470104,knapsack

In [3]:
bench.table

,run_id,experiment_id,benchmark_id,timestamp,energy,energy_min,energy_mean,energy_std,objective,obj_min,...,execution_time,problem_name,instance_name,opt_value,solver,solution_id,knapsack_constraint_violations,knapsack_constraint_violation_min,knapsack_constraint_violation_mean,knapsack_constraint_violation_std
0,d0a656e9-c41a-467d-9d86-5c8608e56f90,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:03.726970,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0]",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,b684deff7ea14b1c9e58a551481687fb,"[143.0, 143.0, 143.0, 143.0, 143.0]",143.0,143.0,0.0
1,69f9e22a-2201-400b-861b-898cd216134a,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:03.833338,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0]",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,615bef24d4344461bc93aaf992c700e9,"[143.0, 143.0, 143.0, 143.0, 143.0]",143.0,143.0,0.0
2,6edfcb35-fa22-45da-9577-8de534452ffa,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:04.281619,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0]",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,5b1ba3f247a0406f80f0d8488998afe6,"[143.0, 143.0, 143.0, 143.0, 143.0]",143.0,143.0,0.0
3,e786a534-7740-4b8d-b4c3-6876138c25f6,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:04.490887,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0]",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,7acfadbfffe044a0a8cd83a7396c4b4e,"[143.0, 143.0, 143.0, 143.0, 143.0]",143.0,143.0,0.0
4,dbe404f3-47d7-4a0e-89d4-7e899d40fdea,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:04.769101,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0]",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,b532cf653fb342b882cb2758f4902db8,"[143.0, 143.0, 143.0, 143.0, 143.0]",143.0,143.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,b0c6e1b7-a7de-45d2-bf27-d9e432ae6491,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:42.681352,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0, -539....",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,8f804ccb60354e17badf4baf84b3c655,"[143.0, 143.0, 143.0, 143.0, 143.0, 143.0, 143...",143.0,143.0,0.0
167,c91c7549-816d-4262-b036-c65fe26730e0,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:43.079755,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0, -539....",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,da90feeea6f340619271bbe9747e77f7,"[143.0, 143.0, 143.0, 143.0, 143.0, 143.0, 143...",143.0,143.0,0.0
168,36df091b-47a4-4219-a38a-59bbb721cc50,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:43.342443,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0, -539....",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,e7931143151445e4a04b24c549cd9c61,"[143.0, 143.0, 143.0, 143.0, 143.0, 143.0, 143...",143.0,143.0,0.0
169,8abd4203-9694-4c9e-9763-38d8c78a6d61,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:43.584422,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0, -539....",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,92cdfb376eb54ec6b049eb71d0449b64,"[143.0, 143.0, 143.0, 143.0, 143.0, 143.0, 143...",143.0,143.0,0.0
170,3c87fd68-c28f-41e5-94ae-44ea311b5d18,f0290ada-d131-4a14-846d-4847e37632a3,09fd5137-5d6a-45c0-b73d-5cc6aa0fe9e0,2022-03-29 12:00:43.940771,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,"[-539.0, -539.0, -539.0, -539.0, -539.0, -539....",-539.0,...,NaN,knapsack,f1_l-d_kp_10_269,NaN,jijzept_sa_sampler_sample_model,644ba4e2c5374780a9b977b35fdee33c,"[143.0, 143.0, 143.0, 143.0, 143.0, 143.0, 143...",143.0,143.0,0.0

In [1]:
import jijzept as jz
import jijbench as jb

def solver_jijzept(solution_id=None):
    sampler = jz.JijSASampler(config="/home/azureuser/.config/jijzept/config.toml")
    response = sampler.get_result(solution_id=solution_id)
    return response, "custom"


bench = jb.Benchmark(
    params={"num_reads": range(5, 15, 5), "num_sweeps": range(10, 20, 10)},
    solvers=[solver_jijzept],
    targets="Knapsack",
    jijzept_config="/home/azureuser/.config/jijzept/config.toml"
)
bench.run(sync=False)

uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 3fcc1f6ccd0244a3b910b783031f2987.
You can access the solution by
>>> a = XXXSampler(config=...)
>>> a.get_result("3fcc1f6ccd0244a3b910b783031f2987")
uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 6b2e66092d624843baf13bae2130c125.
You can access the solution by
>>> a = XXXSampler(config=...)
>>> a.get_result("6b2e66092d624843baf13bae2130c125")

In [2]:
bench.table

,run_id,experiment_id,benchmark_id,timestamp,energy,energy_min,energy_mean,energy_std,objective,obj_min,...,num_feasible,num_samples,sampling_time,execution_time,problem_name,instance_name,opt_value,solver,solution_id,solver_return_values[1]
0,39321d3b-bfda-4a97-8072-2e6e2663b5c8,9d93b1c7-0f49-4014-b087-e9a47fa9a065,f80b901d-7748-4bc2-9d04-425ef2095ef6,2022-03-30 07:55:37.343221,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,NaN,NaN,...,NaN,NaN,160.90204,NaN,knapsack,f1_l-d_kp_10_269,NaN,solver_jijzept,3fcc1f6ccd0244a3b910b783031f2987,custom
1,cedcf2cf-1244-4d10-9693-af54ac17b39e,9d93b1c7-0f49-4014-b087-e9a47fa9a065,f80b901d-7748-4bc2-9d04-425ef2095ef6,2022-03-30 07:55:39.033375,"[-5.673684210526315, -5.673684210526315, -5.67...",-5.673684,-5.673684,0.0,NaN,NaN,...,NaN,NaN,269.000884,NaN,knapsack,f1_l-d_kp_10_269,NaN,solver_jijzept,6b2e66092d624843baf13bae2130c125,custom

In [6]:
bench.evaluate()

/home/azureuser/JijBenchmark/jijbench/evaluation/evaluation.py:132: RuntimeWarning: divide by zero encountered in double_scalars
  return np.log(1 - pr) / np.log(1 - ps) * x.execution_time
/home/azureuser/JijBenchmark/jijbench/evaluation/evaluation.py:132: RuntimeWarning: divide by zero encountered in log
  return np.log(1 - pr) / np.log(1 - ps) * x.execution_time

,success_probability,feasible_rate,residual_energy,TTS(optimal),TTS(feasible),TTS(derived)
0,NaN,0.0,NaN,NaN,-inf,0.0
1,NaN,0.0,NaN,NaN,-inf,0.0

In [6]:
sampler = jz.JijSASampler(config="/home/azureuser/.config/jijzept/config.toml")
sampler.get_result(solution_id="f36e89bb83554f73839b292ec07edeac")

<APIStatus.SUCCESS: 'SUCCESS'>
DimodResponse(rec.array([([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1),
           ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], -5.67368421, 1)],
          dtype=[('sample', 'i1', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8')]), Variables(['x[0]', 'x[1]', 'x[2]', 'x[3]', 'x[4]', 'x[5]', 'x[6]', 'x[7]', 'x[8]', 'x[9]']), {'sampling_time': 308.5043281316757, 'best_parameters': {'parameters': {'linear': {'knapsack_constraint': [[[], 0.0]]}, 'quad': {'knapsack_constraint': [[[], 1e-40]]}}, 'constraint_violations': {'knapsack_constraint': 142.99999999999997}, 'objective': -539.0}}, 'BINARY')

In [5]:
import inspect
import jijzept as jz
import jijbench as jb
from jijbench.solver import DefaultSolver

t = jb.problems.Knapsack()

sampler = jz.JijSASampler(config="/home/azureuser/.config/jijzept/config.toml")
response = sampler.sample_model(t.problem, t.instance[1], sync=False)

uploading instance ...
submitting query ...
submitted to the queue.
Your solution_id is 9dab3a11faad4b68af19e9412b545cc9.
You can access the solution by
>>> a = XXXSampler(config=...)
>>> a.get_result("9dab3a11faad4b68af19e9412b545cc9")

<APIStatus.PENDING: 'PENDING'>
DimodResponse(rec.array([],
          dtype=[('sample', 'i1', (0,)), ('energy', '<i8'), ('num_occurrences', '<i8')]), Variables(), {}, 'BINARY')

In [7]:
import jijbench as jb

response = sampler.get_result("9dab3a11faad4b68af19e9412b545cc9")

experiment = jb.Experiment()

with experiment:
    experiment.store(
        {"response": response}
    )

<APIStatus.SUCCESS: 'SUCCESS'>
  x[0] x[1] x[2] x[3] x[4] x[5] x[6] x[7] x[8] x[9]    energy num_oc.
0    1    1    1    1    1    1    1    1    1    1 -5.673684       1
['BINARY', 1 rows, 1 samples, 10 variables]

In [8]:
experiment.table

,run_id,experiment_id,benchmark_id,timestamp,energy,energy_min,energy_mean,energy_std,objective,obj_min,obj_mean,obj_std,num_occurances,num_reads,num_sweeps,num_feasible,num_samples,sampling_time,execution_time
0,d33d34fb-60aa-40b7-9665-8b29632d900a,79660202-8133-4516-993a-57d320c481db,a5858c24-3e47-4031-bcbe-ae0608bba8e0,2022-03-30 07:06:25.444853,[-5.673684210526315],-5.673684,-5.673684,0.0,NaN,NaN,NaN,NaN,[1],1,NaN,NaN,NaN,309.902942,NaN

In [6]:
import jijmodeling as jm
import inspect

class A:
    def func():
        x = 1
        y = 2
        return 1

inspect.getsource(A.func)

'    def func():\n        x = 1\n        y = 2\n        return 1\n'

In [7]:
x = {"a": 1, "b": 2, "c": 3}
v = [0, 1, 2]

for xi, vi in zip(list(x.keys()), v):
    print(xi, vi)

a 0
b 1
c 2

In [11]:
import itertools

x = {"a": [1, 2, 3], "b": ["x", "y"]}

for r in itertools.product(*x.values()):
    print(r)

(1, 'x')
(1, 'y')
(2, 'x')
(2, 'y')
(3, 'x')
(3, 'y')